# Generated by Django 6.0.7 on 2026-07-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_mfl_code', models.CharField(max_length=50, verbose_name='Facility MFL code')),
                ('site', models.CharField(blank=True, max_length=100)),
                ('assessment_type', models.CharField(max_length=100)),
                ('date_of_assessment', models.DateField()),
                ('time_of_assessment', models.TimeField(blank=True, null=True)),
                ('date_of_previous_assessment', models.DateField(blank=True, null=True)),
                ('facility_type', models.CharField(choices=[('dispensary', 'Dispensary'), ('health_centre', 'Health Centre'), ('sub_county_hospital', 'Sub County Hospital'), ('county_hospital', 'County Hospital'), ('national_hospital', 'National Hospital'), ('other', 'Other')], max_length=30)),
                ('facility_type_other', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(choices=[('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6')], max_length=2)),
                ('affiliation', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('faith_based', 'Faith Based'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20)),
                ('affiliation_other', models.CharField(blank=True, max_length=150)),
                ('partner', models.CharField(blank=True, choices=[('gok', 'GoK'), ('gok_coag', 'GoK Coag'), ('county_government', 'County Government'), ('partner', 'Partner (specify)')], max_length=20)),
                ('partner_specify', models.CharField(blank=True, max_length=200)),
                ('physical_address', models.CharField(blank=True, max_length=255)),
                ('interviewee_name', models.CharField(blank=True, max_length=150)),
                ('interviewee_title', models.CharField(blank=True, max_length=150)),
                ('interviewee_phone', models.CharField(blank=True, max_length=30)),
                ('poc_tests_conducted', models.TextField(blank=True, verbose_name='List of POC tests conducted at this facility')),
                ('assessors', models.CharField(blank=True, max_length=255, verbose_name='Assessor(s)')),
                ('site_supervisor_name', models.CharField(blank=True, max_length=150)),
                ('site_supervisor_date', models.DateField(blank=True, null=True)),
                ('assessor_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(blank=True, max_length=10)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('correction_type', models.CharField(blank=True, choices=[('onsite', 'Onsite'), ('follow_up', 'Follow up')], max_length=10)),
                ('recommendations', models.CharField(blank=True, max_length=500)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_conformities', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='POCTestStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_test', models.CharField(blank=True, max_length=150)),
                ('tests_conducted', models.CharField(blank=True, max_length=50, verbose_name='# of tests conducted (Month/Quarter)')),
                ('positives', models.CharField(blank=True, max_length=50, verbose_name='# Positives (Month/Quarter)')),
                ('negatives', models.CharField(blank=True, max_length=50, verbose_name='# Negatives (Month/Quarter)')),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_stats', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='TestKitAssessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathogen_condition', models.CharField(blank=True, max_length=150, verbose_name='Name of pathogen/condition tested')),
                ('technique', models.CharField(blank=True, max_length=150, verbose_name='Technique of the test')),
                ('kit_name', models.CharField(blank=True, max_length=150, verbose_name='Name of test kit')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_kits', to='assessments.assessment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.PositiveSmallIntegerField()),
                ('item_code', models.CharField(max_length=10)),
                ('response', models.CharField(blank=True, choices=[('Y', 'Yes'), ('P', 'Partial'), ('N', 'No'), ('NA', 'N/A')], max_length=2)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_responses', to='assessments.assessment')),
            ],
            options={
                'unique_together': {('assessment', 'item_code')},
            },
        ),
        migrations.CreateModel(
            name='TestKitResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=10)),
                ('response', models.CharField(blank=True, choices=[('Y', 'Yes'), ('P', 'Partial'), ('N', 'No'), ('NA', 'N/A')], max_length=2)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('test_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.testkitassessed')),
            ],
            options={
                'unique_together': {('test_kit', 'item_code')},
            },
        ),
    ]
