# Generated by Django 6.1 on 2026-08-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfl_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='MFL Code')),
                ('facility_name', models.CharField(max_length=255, verbose_name='Facility Name')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='County')),
                ('sub_county', models.CharField(blank=True, max_length=100, verbose_name='Sub-county')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['facility_name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='last_completed_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='source',
            field=models.CharField(choices=[('live', 'Live Assessment'), ('imported', 'Imported Historical Assessment'), ('test', 'Test Data')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('government', 'Government'), ('private', 'Private'), ('faith_based', 'Faith Based'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='county_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='date_of_assessment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='facility_mfl_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Facility MFL code'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='facility_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('dispensary', 'Dispensary'), ('health_centre', 'Health Centre'), ('sub_county_hospital', 'Sub County Hospital'), ('county_hospital', 'County Hospital'), ('national_hospital', 'National Hospital'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(blank=True, choices=[('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('5', 'Level 5'), ('6', 'Level 6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.facility'),
        ),
    ]
